### ISSUE TITLE
cashed when i try a data set with 80k features

### ISSUE THREAD

**Issue by henrykey** [tgsmith61591/clust4j#2]
Hi, 
I just tried your k-means using a dataset of  1000 rows and 80k features. it crashed with err msg out of memory. is it because array2drowrealmatrix cost too much memory? have any solution for big dataset with this level of features? 

thanks,

henry

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.math3.linear.Array2DRowRealMatrix.copyOut(Array2DRowRealMatrix.java:529)
	at org.apache.commons.math3.linear.Array2DRowRealMatrix.getData(Array2DRowRealMatrix.java:254)
	at com.clust4j.utils.MatUtils.checkDims(MatUtils.java:133)
	at com.clust4j.utils.MatUtils.containsNaN(MatUtils.java:255)
	at com.clust4j.algo.AbstractClusterer.handleData(AbstractClusterer.java:158)
	at com.clust4j.algo.AbstractClusterer.<init>(AbstractClusterer.java:118)
	at com.clust4j.algo.AbstractPartitionalClusterer.<init>(AbstractPartitionalClusterer.java:17)
	at com.clust4j.algo.AbstractCentroidClusterer.<init>(AbstractCentroidClusterer.java:38)
	at com.clust4j.algo.KMeans.<init>(KMeans.java:41)

**Comment by tgsmith61591** [comment]
Hey, Henry. 80k features is a *lot*. How many records are there? In general clustering is a pretty expensive operation and with this level of data, you'll likely need to add to the heap space in the JVM using the `-Xmx` arg.

Otherwise, the reason for this is that the `Array2DRowRealMatrix.getData` operation implicitly copies the internal data matrix so it doesn't pass back a reference. However, you have pointed out a point of optimization from my end on the `checkDims` operation; I can avoid that copying, but you still may see issues given the magnitude of data. How much memory do you have to work with?

**Comment by henrykey** [comment]
thanks for your quick reply. 8G of memory in my computer. I just work in default. I will try to add the heap space. my dataset is quite huge. there are several 10k of records with more than 80k dims. that's a docs classification, so 1000 is just a sample.
 today is my first try. now it works with about 1200 records when mem. released as much as possible at the point to start clusting, and this time dims was reduced to about 46k.
31-一月 22:52:22.267 INFO  CLUST4J: Logging at /tmp/clust4j-kehongwei
31-一月 22:52:22.221 INFO  K-MEANS: checking input data for NaNs serially
31-一月 22:52:24.974 INFO  K-MEANS: initializing KMeans clustering with 1200 x 45934 data matrix
31-一月 22:52:24.975 INFO  K-MEANS: [meta KMeans] model key=bcdd48d9-2fe1-42ad-8d74-36ee66c67118
31-一月 22:52:24.975 INFO  K-MEANS: [meta KMeans] distance metric=Euclidean
31-一月 22:52:24.975 INFO  K-MEANS: [meta KMeans] scale=false
31-一月 22:52:24.976 INFO  K-MEANS: [meta KMeans] force_parallelism=false
31-一月 22:52:24.976 INFO  K-MEANS: [meta KMeans] allow_auto_parallelism=false
31-一月 22:52:25.989 INFO  K-MEANS: [meta KMeans] K=5
31-一月 22:52:25.990 INFO  K-MEANS: [meta KMeans] maxIter=100
31-一月 22:52:25.990 INFO  K-MEANS: [meta KMeans] minChange=0.005
31-一月 22:52:26.005 INFO  K-MEANS: beginning training segmentation for K = 5
31-一月 22:52:26.006 INFO  K-MEANS: training iteration 0; current system cost = null
31-一月 22:54:43.716 INFO  K-MEANS: training iteration 10; current system cost = 6394.984297210412
31-一月 22:55:25.379 INFO  K-MEANS: training reached convergence at iteration 12 (avg iteration time: 00:00:13.797)
31-一月 22:55:25.380 INFO  K-MEANS: Total system cost: 6389.788650500009
31-一月 22:55:25.380 INFO  K-MEANS: model bcdd48d9-2fe1-42ad-8d74-36ee66c67118 completed in 00:02:59.375

**Comment by tgsmith61591** [comment]
Thanks for the update, Henry! I'm glad you were able to get it to work. You've pointed out a good spot in the dim check for some easy optimization; I'll try to push out a patch in a bit, but since it's not critical to functionality, I'm going to go ahead and close this issue.

**Comment by henrykey** [comment]
I didn't find a method to return result of clustering. I think it's cent_to_record. r u gonna to add one?

thanks

henry

**Comment by tgsmith61591** [comment]
Note that the [`fit`](https://github.com/tgsmith61591/clust4j/blob/master/src/com/clust4j/algo/KMeans.java#L224) method returns the fit model. To extract the labels from the clustering operation, see the [`getLabels()`](https://github.com/tgsmith61591/clust4j/blob/master/src/com/clust4j/algo/AbstractCentroidClusterer.java#L83) method. I believe this is what you're looking for.

**Comment by henrykey** [comment]
ok, thanks. I will try now. :)
